### ISSUE TITLE
No org-babel-execute function for zig!

### ISSUE THREAD

**Issue by Pismice** [jolby/ob-zig.el#2]
Hello,

I just installed it the way you said:
/home/tetratrux/.emacs.d/pluginos/ob-zig.el

Add this to my **init.el**
`(add-to-list 'load-path "/home/tetratrux/.emacs.d/pluginos/ob-zig.el")`

Then when i try to execute a basic zig code i get the following error:
_No org-babel-execute function for zig!_

Any idea where that could be coming from please ? :)

**Comment by jolby** [comment]
Hmmm. I haven't played around with emacs/zig for quite a while. I don't have time to jump into this issue, but my first thought is that it could be something simple like you may need to activate the zig language for org-babel as described here:
https://orgmode.org/worg/org-contrib/babel/languages/index.html#configure

In short, you need to ensure that the variable: org-babel-load-languages is set to something like:
((zig . t)
(emacs-lisp . t))

**Comment by Pismice** [comment]
I tried what you said but the error persist.

I tried doing the same using `M-x customize-variable org-babel-load-languages`.
But when trying to insert "_zig_", I get the error "No match", is that normal ?

PS: thank you for your answer :)

**Comment by jolby** [comment]
I just re-read your initial issue message. It doesn't look like you have actually loaded the ob-zig.el file yet (it is on the load path, but hasn't been loaded yet). Try M-x load-file PATH-TO-ob-zig.el RETURN, then try to execute some zig code using org-babel-execute. If this works I'll update the docs.

**Comment by Pismice** [comment]
Seems to be in fact related to that, from what i understood from your repo infos I had give the path of the folder, but it seems that it is only acceptings files, so I tried what you said with: `/home/tetratrux/.emacs.d/pluginos/_ob-zig.el_/**ob-zig.el**'.

I now get the following error while trying to load the file:
`Cannot open load file: No such file or directory, zig-mode`
Which seems to come from line 45 of the file.

**Comment by Pismice** [comment]
It worked now, I just had to do those few steps:
1. Add this to my **init.el**
```
(require 'package)
(setq package-enable-at-startup nil)
 
(add-to-list 'package-archives '("melpa" . "[https://melpa.org/packages/"))](https://melpa.org/packages/%22)))
(add-to-list 'package-archives '("gnu-devel" . "[https://elpa.gnu.org/devel/"))](https://elpa.gnu.org/devel/%22)))
(add-to-list 'package-archives '("gnu" . "[https://elpa.gnu.org/packages/"))](https://elpa.gnu.org/packages/%22)))

(package-initialize)
 
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
```
2. Install **zig-mode**
`M+x list-packages zig-mode` (install zig-mode)

3. Load your config file
`M-x load-file PATH-TO-ob-zig.el`

After that I could use C-c C-c to run zig code and have basic syntax highlighting
